
#eureka:
#    client:
#        serviceUrl:
#            defaultZone: http://localhost:8761/eureka

server:
    port: 8081



spring:
    application:
        name: admin-app
    datasource:
        password: Subasil@8086
        url: jdbc:mysql://localhost:3306/admin
        username: root
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect
                format_sql: true
        show-sql: true
    main:
        allow-circular-references: true
